#ifndef GAMESERVER_DIRECTION_HPP
#define GAMESERVER_DIRECTION_HPP

enum class Direction {
    NORTH,
    NORTHEAST,
    EAST,
    SOUTHEAST,
    SOUTH,
    SOUTHWEST,
    WEST,
    NORTHWEST
};

#endif //GAMESERVER_DIRECTION_HPP
