name: BuildServer
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        bash build.sh
